#!/usr/bin/with-contenv bash

# Kill left over FFmpeg and GStreamer processes in case of a restart
pkill -f ffmpeg_
pkill -f gstreamer_

cd /src
exec justc-envdir /var/run/environment s6-setuidgid abc exec -a "viseron" python3 -u -m viseron
