# Inspired by https://github.com/jrottenberg/ffmpeg/
ARG CMAKE_VERSION
ARG UBUNTU_VERSION
ARG PREFIX=/opt/ffmpeg
FROM roflcoopter/rpi3-cmake:${CMAKE_VERSION}-${UBUNTU_VERSION} as cmake
FROM balenalib/raspberrypi3-ubuntu:${UBUNTU_VERSION}-build as build
RUN [ "cross-build-start" ]

COPY --from=cmake /usr/custom_cmake/bin /usr/custom_cmake/bin/
COPY --from=cmake /usr/custom_cmake/share /usr/custom_cmake/share/

WORKDIR /tmp/workdir

ARG MAKEFLAGS="-j2"

ENV \
  DEBIAN_FRONTEND=noninteractive \
  SRC=/usr/local \
  PATH=/usr/custom_cmake/bin:$PATH \
  PKG_CONFIG_PATH="/opt/ffmpeg/share/pkgconfig:/opt/ffmpeg/lib/pkgconfig:/opt/ffmpeg/lib64/pkgconfig" \
  LD_LIBRARY_PATH="/opt/ffmpeg/lib:/opt/ffmpeg/lib64:/usr/lib64:/usr/lib:/lib64:/lib:/opt/vc/lib"

RUN buildDeps="autoconf \
  automake \
  ca-certificates \
  curl \
  bzip2 \
  libexpat1-dev \
  g++ \
  gcc \
  git \
  gperf \
  libtool \
  make \
  meson \
  nasm \
  ninja-build \
  perl \
  pkg-config \
  python3 \
  python3-pip \
  libssl-dev \
  yasm \
  libgomp1 \
  zlib1g-dev \
  libx265-dev \
  libomxil-bellagio-dev \
  libharfbuzz-dev \
  xz-utils" && \
  apt-get -yqq update && \
  apt-get install -yq --no-install-recommends ${buildDeps}

### opencore-amr https://sourceforge.net/projects/opencore-amr/
FROM build as opencoreamr
ARG PREFIX
ARG OPENCOREAMR_VERSION
RUN \
  DIR=/tmp/opencore-amr && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://sourceforge.net/projects/opencore-amr/files/opencore-amr/opencore-amr-${OPENCOREAMR_VERSION}.tar.gz/download | \
  tar -zx --strip-components=1 && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### x264 http://www.videolan.org/developers/x264.html
ARG X264_VERSION
RUN \
  DIR=/tmp/x264 && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://download.videolan.org/pub/videolan/x264/snapshots/x264-snapshot-${X264_VERSION}.tar.bz2 | \
  tar -jx --strip-components=1 && \
  ./configure --prefix="${PREFIX}" --enable-static --enable-pic --disable-cli && \
  make && \
  make install && \
  rm -rf ${DIR}
### x265 http://x265.org/
# Can't build this on ARM, installed from apt instead
# ARG X265_VERSION
# RUN \
#   DIR=/tmp/x265 && \
#   mkdir -p ${DIR} && \
#   cd ${DIR} && \
#   curl -sL https://download.videolan.org/pub/videolan/x265/x265_${X265_VERSION}.tar.gz  | \
#   tar -zx && \
#   cd x265_${X265_VERSION}/build/linux && \
#   sed -i "/-DEXTRA_LIB/ s/$/ -DCMAKE_INSTALL_PREFIX=\${PREFIX}/" multilib.sh && \
#   sed -i "/^cmake/ s/$/ -DENABLE_CLI=OFF/" multilib.sh && \
#   export CXXFLAGS="${CXXFLAGS} -fPIC" && \
#   ./multilib.sh && \
#   make -C 8bit install && \
#   rm -rf ${DIR}
### libogg https://www.xiph.org/ogg/
ARG OGG_VERSION
ARG OGG_SHA256SUM
RUN \
  DIR=/tmp/ogg && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO http://downloads.xiph.org/releases/ogg/libogg-${OGG_VERSION}.tar.gz && \
  echo ${OGG_SHA256SUM} | sha256sum --check && \
  tar -zx --strip-components=1 -f libogg-${OGG_VERSION}.tar.gz && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### libopus https://www.opus-codec.org/
ARG OPUS_VERSION
ARG OPUS_SHA256SUM
RUN \
  DIR=/tmp/opus && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://github.com/xiph/opus/releases/download/v${OPUS_VERSION}/opus-${OPUS_VERSION}.tar.gz && \
  echo ${OPUS_SHA256SUM} | sha256sum --check && \
  tar -zx --strip-components=1 -f opus-${OPUS_VERSION}.tar.gz
RUN ["cross-build-end"]
RUN \
  DIR=/tmp/opus && \
  cd ${DIR} && \
  autoreconf -fiv
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/opus && \
  cd ${DIR} && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### libvorbis https://xiph.org/vorbis/
ARG VORBIS_VERSION
ARG VORBIS_SHA256SUM
RUN \
  DIR=/tmp/vorbis && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO http://downloads.xiph.org/releases/vorbis/libvorbis-${VORBIS_VERSION}.tar.gz && \
  echo ${VORBIS_SHA256SUM} | sha256sum --check && \
  tar -zx --strip-components=1 -f libvorbis-${VORBIS_VERSION}.tar.gz && \
  ./configure --prefix="${PREFIX}" --with-ogg="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### libtheora http://www.theora.org/
ARG THEORA_VERSION
ARG THEORA_SHA256SUM
RUN \
  DIR=/tmp/theora && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://downloads.xiph.org/releases/theora/libtheora-${THEORA_VERSION}.tar.gz && \
  echo ${THEORA_SHA256SUM} | sha256sum --check && \
  tar -zx --strip-components=1 -f libtheora-${THEORA_VERSION}.tar.gz && \
  curl -fsSLo config.guess "https://git.savannah.gnu.org/cgit/config.git/plain/config.guess" && \
  curl -fsSLo config.sub "https://git.savannah.gnu.org/cgit/config.git/plain/config.sub" && \
  ./configure --prefix="${PREFIX}" --with-ogg="${PREFIX}" --enable-static --disable-shared --disable-examples && \
  make && \
  make install && \
  rm -rf ${DIR}
### libvpx https://www.webmproject.org/code/
FROM build as vpx
ARG PREFIX
ARG VPX_VERSION
RUN \
  DIR=/tmp/vpx && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://codeload.github.com/webmproject/libvpx/tar.gz/v${VPX_VERSION} | \
  tar -zx --strip-components=1 && \
  ./configure --prefix="${PREFIX}" --enable-vp8 --enable-vp9 --enable-vp9-highbitdepth --enable-pic --disable-shared \
  --disable-debug --disable-examples --disable-docs --disable-install-bins  && \
  make && \
  make install && \
  rm -rf ${DIR}
### libwebp https://developers.google.com/speed/webp/
FROM build as webp
ARG PREFIX
ARG WEBP_VERSION
RUN \
  DIR=/tmp/webp && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-${WEBP_VERSION}.tar.gz | \
  tar -zx --strip-components=1 && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### libmp3lame http://lame.sourceforge.net/
ARG LAME_VERSION
RUN \
  DIR=/tmp/lame && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://sourceforge.net/projects/lame/files/lame/${LAME_VERSION}/lame-${LAME_VERSION}.tar.gz/download | \
  tar -zx --strip-components=1 && \
  ./configure --prefix="${PREFIX}" --bindir="${PREFIX}/bin" --enable-static --disable-shared --enable-nasm --disable-frontend && \
  make && \
  make install && \
  rm -rf ${DIR}
### xvid https://www.xvid.com/
ARG XVID_VERSION
ARG XVID_SHA256SUM
RUN \
  DIR=/tmp/xvid && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://downloads.xvid.com/downloads/xvidcore-${XVID_VERSION}.tar.gz && \
  echo ${XVID_SHA256SUM} | sha256sum --check && \
  tar -zx -f xvidcore-${XVID_VERSION}.tar.gz && \
  cd xvidcore/build/generic && \
  ./configure --prefix="${PREFIX}" --bindir="${PREFIX}/bin" --disable-shared --enable-static && \
  make && \
  make install && \
  rm -f ${PREFIX}/lib/libxvidcore.so* && \
  rm -rf ${DIR}
### fdk-aac https://github.com/mstorsjo/fdk-aac
FROM build as fdkaac
ARG PREFIX
ARG FDKAAC_VERSION
RUN \
  DIR=/tmp/fdk-aac && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://github.com/mstorsjo/fdk-aac/archive/v${FDKAAC_VERSION}.tar.gz | \
  tar -zx --strip-components=1
RUN ["cross-build-end"]
RUN \
  DIR=/tmp/fdk-aac && \
  cd ${DIR} && \
  autoreconf -fiv
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/fdk-aac && \
  cd ${DIR} && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared --datadir="${DIR}" && \
  make && \
  make install && \
  rm -rf ${DIR}
### openjpeg https://github.com/uclouvain/openjpeg
ARG OPENJPEG_VERSION
RUN \
  DIR=/tmp/openjpeg && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://github.com/uclouvain/openjpeg/archive/v${OPENJPEG_VERSION}.tar.gz | \
  tar -zx --strip-components=1 && \
  export CFLAGS="${CFLAGS} -DPNG_ARM_NEON_OPT=0" && \
  cmake -DBUILD_THIRDPARTY:BOOL=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="${PREFIX}" . && \
  make && \
  make install && \
  rm -rf ${DIR}
### freetype https://www.freetype.org/
ARG FREETYPE_VERSION
ARG FREETYPE_SHA256SUM
RUN  \
  DIR=/tmp/freetype && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO http://download.savannah.gnu.org/releases/freetype/freetype-${FREETYPE_VERSION}.tar.gz && \
  echo ${FREETYPE_SHA256SUM} | sha256sum --check && \
  tar -zx --strip-components=1 -f freetype-${FREETYPE_VERSION}.tar.gz && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### libvstab https://github.com/georgmartius/vid.stab
ARG LIBVIDSTAB_VERSION
ARG LIBVIDSTAB_SHA256SUM
RUN  \
  DIR=/tmp/vid.stab && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL -o vid.stab-${LIBVIDSTAB_VERSION}.tar.gz https://github.com/georgmartius/vid.stab/archive/v${LIBVIDSTAB_VERSION}.tar.gz && \
  echo ${LIBVIDSTAB_SHA256SUM} | sha256sum --check &&  \
  tar -zx --strip-components=1 -f vid.stab-${LIBVIDSTAB_VERSION}.tar.gz && \
  cmake -DCMAKE_INSTALL_PREFIX="${PREFIX}" -DSSE2_FOUND=OFF -DBUILD_SHARED_LIBS=OFF . && \
  make && \
  make install && \
  rm -rf ${DIR}
### fribidi https://www.fribidi.org/
ARG FRIBIDI_VERSION
ARG FRIBIDI_SHA256SUM
RUN  \
  DIR=/tmp/fribidi && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL -o fribidi-${FRIBIDI_VERSION}.tar.gz https://github.com/fribidi/fribidi/archive/refs/tags/v${FRIBIDI_VERSION}.tar.gz && \
  echo ${FRIBIDI_SHA256SUM} | sha256sum --check && \
  tar -zx --strip-components=1 -f fribidi-${FRIBIDI_VERSION}.tar.gz
RUN ["cross-build-end"]
RUN \
  export NOCONFIGURE=1 && \
  DIR=/tmp/fribidi && \
  cd ${DIR} && \
  ./autogen.sh
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/fribidi && \
  cd ${DIR} && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  # Use -j1 because fribidi breaks when building in parallel and c2man is not installed
  make -j1 && \
  make install && \
  rm -rf ${DIR}
### fontconfig https://www.freedesktop.org/wiki/Software/fontconfig/
ARG FONTCONFIG_VERSION
RUN  \
  DIR=/tmp/fontconfig && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://www.freedesktop.org/software/fontconfig/release/fontconfig-${FONTCONFIG_VERSION}.tar.gz && \
  tar -zx --strip-components=1 -f fontconfig-${FONTCONFIG_VERSION}.tar.gz && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### libass https://github.com/libass/libass
ARG LIBASS_VERSION
ARG LIBASS_SHA256SUM
RUN  \
  DIR=/tmp/libass && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://github.com/libass/libass/archive/${LIBASS_VERSION}.tar.gz && \
  echo ${LIBASS_SHA256SUM} | sha256sum --check && \
  tar -zx --strip-components=1 -f ${LIBASS_VERSION}.tar.gz
RUN ["cross-build-end"]
RUN \
  DIR=/tmp/libass && \
  cd ${DIR} && \
  ./autogen.sh
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/libass && \
  cd ${DIR} && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### kvazaar https://github.com/ultravideo/kvazaar
ARG KVAZAAR_VERSION
RUN \
  DIR=/tmp/kvazaar && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://github.com/ultravideo/kvazaar/archive/v${KVAZAAR_VERSION}.tar.gz && \
  tar -zx --strip-components=1 -f v${KVAZAAR_VERSION}.tar.gz
RUN ["cross-build-end"]
RUN \
  DIR=/tmp/kvazaar && \
  cd ${DIR} && \
  ./autogen.sh
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/kvazaar && \
  cd ${DIR} && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### aom https://aomedia.googlesource.com/aom
FROM build as aom
ARG PREFIX
ARG AOM_VERSION
RUN \
  DIR=/tmp/aom && \
  git clone --branch v${AOM_VERSION} --depth 1 https://aomedia.googlesource.com/aom ${DIR} && \
  cd ${DIR} && \
  rm -rf CMakeCache.txt CMakeFiles && \
  mkdir -p ./aom_build && \
  cd ./aom_build && \
  cmake -DCMAKE_INSTALL_PREFIX="${PREFIX}" -DAOM_TARGET_CPU=arm -DENABLE_NEON=0 -DENABLE_TESTS=0 -DBUILD_SHARED_LIBS=OFF .. && \
  make && \
  make install && \
  rm -rf ${DIR}
### libxcb (and supporting libraries) for screen capture https://xcb.freedesktop.org/
ARG XORG_MACROS_VERSION
RUN \
  DIR=/tmp/xorg-macros && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://www.x.org/archive//individual/util/util-macros-${XORG_MACROS_VERSION}.tar.gz && \
  tar -zx --strip-components=1 -f util-macros-${XORG_MACROS_VERSION}.tar.gz && \
  ./configure --srcdir=${DIR} --prefix="${PREFIX}" && \
  make && \
  make install && \
  rm -rf ${DIR}

ARG XPROTO_VERSION
RUN \
  DIR=/tmp/xproto && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://www.x.org/archive/individual/proto/xproto-${XPROTO_VERSION}.tar.gz && \
  tar -zx --strip-components=1 -f xproto-${XPROTO_VERSION}.tar.gz && \
  ./configure --srcdir=${DIR} --prefix="${PREFIX}" && \
  make && \
  make install && \
  rm -rf ${DIR}

ARG XAU_VERSION
RUN \
  DIR=/tmp/libXau && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://www.x.org/archive/individual/lib/libXau-${XAU_VERSION}.tar.gz && \
  tar -zx --strip-components=1 -f libXau-${XAU_VERSION}.tar.gz && \
  ./configure --srcdir=${DIR} --prefix="${PREFIX}" && \
  make && \
  make install && \
  rm -rf ${DIR}

ARG LIBPTHREAD_STUBS_VERSION
RUN \
  DIR=/tmp/libpthread-stubs && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://xcb.freedesktop.org/dist/libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
  tar -zx --strip-components=1 -f libpthread-stubs-${LIBPTHREAD_STUBS_VERSION}.tar.gz && \
  ./configure --prefix="${PREFIX}" && \
  make && \
  make install && \
  rm -rf ${DIR}
### libxml2
ARG LIBXML2_VERSION
ARG LIBXML2_SHA256SUM
RUN \
  DIR=/tmp/libxml2 && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://gitlab.gnome.org/GNOME/libxml2/-/archive/v${LIBXML2_VERSION}/libxml2-v${LIBXML2_VERSION}.tar.gz && \
  echo ${LIBXML2_SHA256SUM} | sha256sum --check && \
  tar -xz --strip-components=1 -f libxml2-v${LIBXML2_VERSION}.tar.gz
RUN ["cross-build-end"]
RUN \
  DIR=/tmp/libxml2 && \
  cd ${DIR} && \
  ./autogen.sh --prefix="${PREFIX}" --with-ftp=no --with-http=no --with-python=no --enable-static --disable-shared
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/libxml2 && \
  cd ${DIR} && \
  make && \
  make install && \
  rm -rf ${DIR}
### libzmq https://github.com/zeromq/libzmq/
FROM build as zmq
ARG PREFIX
ARG LIBZMQ_VERSION
ARG LIBZMQ_SHA256SUM
RUN \
  DIR=/tmp/libzmq && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sLO https://github.com/zeromq/libzmq/archive/v${LIBZMQ_VERSION}.tar.gz && \
  echo ${LIBZMQ_SHA256SUM} | sha256sum --check && \
  tar -xz --strip-components=1 -f v${LIBZMQ_VERSION}.tar.gz
RUN ["cross-build-end"]
RUN \
  DIR=/tmp/libzmq && \
  cd ${DIR} && \
  ./autogen.sh
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/libzmq && \
  cd ${DIR} && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### libpng http://www.libpng.org/pub/png/libpng.html
FROM build as libpng
ARG PREFIX
ARG LIBPNG_VERSION
RUN \
  DIR=/tmp/libpng && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -L https://downloads.sourceforge.net/project/libpng/libpng16/${LIBPNG_VERSION}/libpng-${LIBPNG_VERSION}.tar.xz | \
  tar -Jx --strip-components=1 && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### libsrt https://github.com/Haivision/srt
FROM build as libsrt
ARG PREFIX
ARG LIBSRT_VERSION
RUN \
  DIR=/tmp/srt && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://github.com/Haivision/srt/archive/refs/tags/v${LIBSRT_VERSION}.tar.gz | \
  tar -zx --strip-components=1 && \
  cmake -DCMAKE_INSTALL_PREFIX="${PREFIX}" -DENABLE_SHARED=OFF -DENABLE_STATIC=ON . && \
  make && \
  make install && \
  rm -rf ${DIR}
### libvmaf https://github.com/Netflix/vmaf
FROM build as libvmaf
ARG PREFIX
ARG LIBVMAF_VERSION
RUN \
  DIR=/tmp/vmaf && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://github.com/Netflix/vmaf/archive/refs/tags/v${LIBVMAF_VERSION}.tar.gz | \
  tar -zx --strip-components=1 && \
  cd libvmaf && \
  meson setup \
  --prefix="${PREFIX}" \
  --buildtype=release \
  --default-library=static \
  --libdir="${PREFIX}/lib" \
  -Denable_tests=false \
  -Denable_docs=false \
  build && \
  ninja -C build && \
  ninja -C build install && \
  rm -rf ${DIR}
### libaribb24 https://github.com/nkoriyama/aribb24
FROM build as libaribb24
ARG PREFIX
ARG LIBARIBB24_VERSION
RUN \
  DIR=/tmp/b24 && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://github.com/nkoriyama/aribb24/archive/refs/tags/v${LIBARIBB24_VERSION}.tar.gz | \
  tar -zx --strip-components=1 && \
  mkdir -p m4
RUN ["cross-build-end"]
RUN \
  DIR=/tmp/b24 && \
  cd ${DIR} && \
  autoreconf -fiv
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/b24 && \
  cd ${DIR} && \
  ./configure CFLAGS="-I${PREFIX}/include -fPIC" --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### zimg https://github.com/sekrit-twc/zimg
FROM build as zimg
ARG PREFIX
ARG ZIMG_VERSION
RUN \
  DIR=/tmp/zimg && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  curl -sL https://github.com/sekrit-twc/zimg/archive/refs/tags/release-${ZIMG_VERSION}.tar.gz | \
  tar -zx --strip-components=1
RUN ["cross-build-end"]
RUN \
  DIR=/tmp/zimg && \
  cd ${DIR} && \
  ./autogen.sh
RUN ["cross-build-start"]
RUN \
  DIR=/tmp/zimg && \
  cd ${DIR} && \
  ./configure --prefix="${PREFIX}" --enable-static --disable-shared && \
  make && \
  make install && \
  rm -rf ${DIR}
### userland https://github.com/raspberrypi/userland
FROM build as ffmpeg
ARG PREFIX
COPY --from=opencoreamr /opt/ffmpeg /opt/ffmpeg
COPY --from=vpx /opt/ffmpeg /opt/ffmpeg
COPY --from=webp /opt/ffmpeg /opt/ffmpeg
COPY --from=fdkaac /opt/ffmpeg /opt/ffmpeg
COPY --from=aom /opt/ffmpeg /opt/ffmpeg
COPY --from=zmq /opt/ffmpeg /opt/ffmpeg
COPY --from=libpng /opt/ffmpeg /opt/ffmpeg
COPY --from=libsrt /opt/ffmpeg /opt/ffmpeg
COPY --from=libvmaf /opt/ffmpeg /opt/ffmpeg
COPY --from=libaribb24 /opt/ffmpeg /opt/ffmpeg
COPY --from=zimg /opt/ffmpeg /opt/ffmpeg
RUN \
  DIR=/tmp/userland && \
  mkdir -p ${DIR} && \
  cd ${DIR} && \
  git clone --depth 1 https://github.com/raspberrypi/userland.git . && \
  ./buildme && \
  rm -rf ${DIR} && \
  echo "/opt/vc/lib" > /etc/ld.so.conf.d/00-vmcs.conf && \
  ldconfig
### ffmpeg https://ffmpeg.org/
ARG FFMPEG_VERSION
RUN  \
  ls -al /opt/ffmpeg && \
  DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && \
  curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
  tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
  DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && \
  ./configure \
  --disable-debug \
  --disable-doc \
  --disable-ffplay \
  --enable-static \
  --disable-shared \
  --pkg-config-flags="--static" \
  --enable-libopencore-amrnb \
  --enable-libopencore-amrwb \
  --enable-gpl \
  --enable-libaribb24 \
  --enable-libass \
  --enable-fontconfig \
  --enable-libfreetype \
  --enable-libvidstab \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libsrt \
  --enable-libtheora \
  --enable-libvmaf \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libwebp \
  --enable-libxcb \
  --enable-libx265 \
  --enable-libxvid \
  --enable-libx264 \
  --enable-libzimg \
  --enable-nonfree \
  --enable-openssl \
  --enable-libfdk_aac \
  --enable-small \
  --enable-version3 \
  --enable-libzmq \
  --prefix="${PREFIX}" \
  --enable-libopenjpeg \
  --enable-libkvazaar \
  --enable-libaom \
  --enable-mmal \
  --enable-neon \
  --enable-omx \
  --enable-omx-rpi \
  --enable-v4l2_m2m \
  --extra-cflags="-I${PREFIX}/include" \
  --extra-ldflags="-L${PREFIX}/lib" \
  --extra-libs="-ldl -lpthread -lm -lz -lstdc++" && \
  make && \
  make install && \
  make tools/zmqsend && cp tools/zmqsend ${PREFIX}/bin/ && \
  make distclean && \
  hash -r && \
  cd tools && \
  make qt-faststart && cp qt-faststart ${PREFIX}/bin/

### cleanup
RUN \
  cp ${PREFIX}/bin/ffmpeg /usr/local/bin/ && \
  cp ${PREFIX}/bin/ffprobe /usr/local/bin/ && \
  cp ${PREFIX}/bin/zmqsend /usr/local/bin/ && \
  cp ${PREFIX}/bin/qt-faststart /usr/local/bin/ && \
  cp -r ${PREFIX}/share/ffmpeg /usr/local/share/

RUN [ "cross-build-end" ]

FROM scratch
COPY --from=ffmpeg /usr/local/bin /usr/local/bin/
COPY --from=ffmpeg /usr/local/share /usr/local/share/
COPY --from=ffmpeg /opt/vc/lib /opt/vc/lib
