#!/usr/bin/with-contenv bash
#
source /helpers/logger.sh
source /helpers/set_env.sh

log_info "Wait for Viseron to stop..."
PID=$(pgrep -f ^viseron)
while ps -p $PID > /dev/null; do
  sleep 1
done
log_info "Viseron has stopped!"

log_info "Stopping PostgreSQL..."
s6-setuidgid postgres $PG_BIN/pg_ctl -D $VISERON_CONFIG_DIR/postgresql -l $VISERON_CONFIG_DIR/postgresql/logfile stop

# Wait until PostgreSQL has stopped
log_info "Waiting for PostgreSQL Server to stop..."
while s6-setuidgid abc pg_isready -d viseron; do
  sleep 1
done
log_info "PostgreSQL Server has stopped!"

# Restore permissions
chown -R abc:abc $VISERON_CONFIG_DIR/postgresql
