#!/usr/bin/with-contenv bash

source /helpers/logger.sh
source /helpers/set_env.sh

if [ -n "$POSTGRES_DATABASE_URL" ]; then
  log_info "POSTGRES_DATABASE_URL is set. Won't start local PostgreSQL server."
  # Start a dummy process to keep s6 happy
  exec s6-pause
  exit 0
fi

rm -f $VISERON_CONFIG_DIR/postgres.log

log_info "Starting PostgreSQL Server..."
exec s6-setuidgid postgres $PG_BIN/postgres -D $PGDATA 2>&1 | tee -a $VISERON_CONFIG_DIR/postgres.log
