"""Telegram-PTZ component constants."""

COMPONENT = "ptz"
DESC_COMPONENT = "Telegram bot to control pan-tilt-zoom cameras."

CONFIG_CAMERA_PORT = "onvif_port"
CONFIG_CAMERA_USERNAME = "onvif_username"
CONFIG_CAMERA_PASSWORD = "onvif_password"
CONFIG_CAMERA_FULL_SWING_MIN_X = "camera_min_x"
CONFIG_CAMERA_FULL_SWING_MAX_X = "camera_max_x"
CONFIG_PTZ_PRESETS = "presets"
CONFIG_PRESET_NAME = "name"
CONFIG_PRESET_X = "x"
CONFIG_PRESET_Y = "y"
CONFIG_PRESET_Z = "z"
CONFIG_PRESET_ON_STARTUP = "on_startup"
CONFIG_HOST = "host"

CONFIG_CAMERAS = "cameras"

DESC_CAMERA_PORT = "ONVIF port of the camera."
DESC_CAMERA_USERNAME = "ONVIF username for the camera."
DESC_CAMERA_PASSWORD = "ONVIF password for the camera."
DESC_CAMERA_FULL_SWING_MIN_X = "Minimum pan value of the camera."
DESC_CAMERA_FULL_SWING_MAX_X = "Maximum pan value of the camera."
DESC_PTZ_PRESET = "List of PTZ presets."
DESC_PRESET_NAME = "Name of the PTZ preset."
DESC_PRESET_X = "Pan value of the PTZ preset."
DESC_PRESET_Y = "Tilt value of the PTZ preset."
DESC_PRESET_Z = "Zoom value of the PTZ preset."
DESC_PRESET_ON_STARTUP = "Move to this PTZ preset on startup."

DESC_CAMERAS = "List of ONVIF cameras to control."
