ARG ARCH
ARG VISERON_VERSION
FROM roflcoopter/${ARCH}-viseron:${VISERON_VERSION}

WORKDIR /src

ENV VISERON_TESTS=true

ADD requirements_test.txt requirements_test.txt
RUN \
  python3 -m pip install -r requirements_test.txt

RUN rm -r /etc/services.d/viseron \
  && mkdir -p /config \
  && mkdir -p /event_clips \
  && mkdir -p /segments \
  && mkdir -p /snapshots\
  && mkdir -p /thumbnails

COPY .coveragerc /src/
COPY viseron /src/viseron/
COPY tests /src/tests/
