ARG ARCH
ARG WHEELS_VERSION
ARG UBUNTU_VERSION
ARG VISERON_VERSION
FROM roflcoopter/${ARCH}-wheels:${WHEELS_VERSION}-${UBUNTU_VERSION} AS wheels
FROM roflcoopter/${ARCH}-viseron:${VISERON_VERSION}

WORKDIR /src

ENV VISERON_TESTS=true

COPY .coveragerc /src/
COPY manager.py /src/manager.py
COPY rootfs/ /
COPY --from=wheels /wheels /wheels
COPY requirements.txt requirements.txt
COPY requirements_test.txt requirements_test.txt
RUN \
  python3 -m pip install /wheels/*.whl \
  && python3 -m pip install -r requirements_test.txt \
  && rm -r /wheels \
  && rm -r /etc/services.d/viseron \
  && mkdir -p /config \
  && mkdir -p /event_clips \
  && mkdir -p /segments \
  && mkdir -p /snapshots\
  && mkdir -p /thumbnails

COPY viseron /src/viseron/
COPY tests /src/tests/
