ARG UBUNTU_VERSION
FROM ubuntu:${UBUNTU_VERSION} as base

RUN \
  apt-get update && apt-get install -y --no-install-recommends \
  ca-certificates \
  wget 

# EdgeTPU MobileNet SSD v2 Object Detection model
RUN \
  mkdir -p /detectors/models/edgetpu/classification && \
  wget https://github.com/google-coral/test_data/raw/master/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite -O /detectors/models/edgetpu/model.tflite --progress=bar:force:noscroll && \
  wget https://github.com/google-coral/test_data/raw/master/ssd_mobilenet_v2_coco_quant_postprocess.tflite         -O /detectors/models/edgetpu/cpu_model.tflite --progress=bar:force:noscroll && \
  wget https://github.com/google-coral/test_data/raw/master/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite  -O /detectors/models/edgetpu/mobiledet_model.tflite --progress=bar:force:noscroll && \
  wget https://github.com/google-coral/test_data/raw/master/ssdlite_mobiledet_coco_qat_postprocess.tflite          -O /detectors/models/edgetpu/mobiledet_cpu_model.tflite --progress=bar:force:noscroll && \
  wget https://github.com/google-coral/test_data/raw/master/coco_labels.txt -O /detectors/models/edgetpu/labels.txt --progress=bar:force:noscroll 

# Fetch models for YOLOv4 darknet
RUN \
  mkdir -p /detectors/models/darknet && \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights -O /detectors/models/darknet/yolov4.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/coco.names -O /detectors/models/darknet/coco.names --progress=bar:force:noscroll

# Fetch models for YOLOv4-tiny darknet
RUN \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-tiny.weights -O /detectors/models/darknet/yolov4-tiny.weights --progress=bar:force:noscroll

# Fetch models for YOLOv4-p6 darknet
RUN \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-p6.weights -O /detectors/models/darknet/yolov4-p6.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-p6.cfg -O /detectors/models/darknet/yolov4-p6.cfg --progress=bar:force:noscroll

# Fetch models for YOLOv4-p5 darknet
RUN \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-p5.weights -O /detectors/models/darknet/yolov4-p5.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-p5.cfg -O /detectors/models/darknet/yolov4-p5.cfg --progress=bar:force:noscroll

# Fetch models for YOLOv4-csp-x-swish darknet
RUN \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp-x-swish.weights -O /detectors/models/darknet/yolov4-csp-x-swish.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp-x-swish.cfg -O /detectors/models/darknet/yolov4-csp-x-swish.cfg --progress=bar:force:noscroll

# Fetch models for YOLOv4-csp-swish darknet
RUN \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp-swish.weights -O /detectors/models/darknet/yolov4-csp-swish.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp-swish.cfg -O /detectors/models/darknet/yolov4-csp-swish.cfg --progress=bar:force:noscroll

# Fetch models for YOLOv4x-mish darknet
RUN \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4x-mish.weights -O /detectors/models/darknet/yolov4x-mish.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4x-mish.cfg -O /detectors/models/darknet/yolov4x-mish.cfg --progress=bar:force:noscroll

# Fetch models for YOLOv4-csp darknet
RUN \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v4_pre/yolov4-csp.weights -O /detectors/models/darknet/yolov4-csp.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov4-csp.cfg -O /detectors/models/darknet/yolov4-csp.cfg --progress=bar:force:noscroll

# Fetch models for YOLOv3 darknet
RUN \
  wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov3.weights -O /detectors/models/darknet/yolov3.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/yolov3.cfg -O /detectors/models/darknet/yolov3.cfg --progress=bar:force:noscroll

# Fetch models for YOLOv3-tiny darknet
RUN \
  wget https://pjreddie.com/media/files/yolov3-tiny.weights -O /detectors/models/darknet/yolov3-tiny.weights --progress=bar:force:noscroll && \
  wget https://raw.githubusercontent.com/pjreddie/darknet/master/cfg/yolov3-tiny.cfg -O /detectors/models/darknet/yolov3-tiny.cfg --progress=bar:force:noscroll

ADD ./docker/yolov4.cfg /detectors/models/darknet/yolov4.cfg
ADD ./docker/yolov4-tiny.cfg /detectors/models/darknet/yolov4-tiny.cfg

FROM scratch

COPY --from=base /detectors /detectors
