FROM roflcoopter/amd64-viseron:dev

ENV SHELL /bin/bash

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    curl \
    && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install --no-install-recommends -y \
    nodejs

COPY requirements_test.txt requirements_test.txt
RUN pip3 install -r requirements_test.txt \
    && yes | mypy --install-types || true \
    && rm -rf requirements_test.txt

RUN rm -r /etc/services.d/viseron

# Ensure at least the en_US.UTF-8 UTF-8 locale is available.
RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && echo "LANG=en_US.UTF-8" > /etc/locale.conf \
    && locale-gen en_US.UTF-8

WORKDIR /workspaces/viseron