FROM roflcoopter/amd64-viseron:dev

ENV SHELL /bin/bash

RUN apt-get update \
    && apt-get install --no-install-recommends -y \
    build-essential \
    cmake \
    git \
    curl \
    locales \
    libcairo2-dev \
    libgirepository1.0-dev \
    python3-dev \
    python3.9-dev \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install --no-install-recommends -y \
    nodejs \
    && npm install -g npm@latest \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements_test.txt requirements_test.txt
RUN python3 -m pip install -r requirements_test.txt \
    && yes | mypy --install-types || true \
    && rm -rf requirements_test.txt

RUN rm -r /etc/services.d/viseron \
    && mkdir -p /config \
    && mkdir -p /event_clips \
    && mkdir -p /segments \
    && mkdir -p /snapshots\
    && mkdir -p /thumbnails

# Ensure at least the en_US.UTF-8 UTF-8 locale is available.
RUN echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
    && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
    && echo "LANG=en_US.UTF-8" > /etc/locale.conf \
    && locale-gen en_US.UTF-8

WORKDIR /workspaces/viseron