#!/bin/bash

# This script wraps the FFprobe executable to supply correct LD_LIBRARY_PATH.
# Previously FFmpeg was copied to /usr/local but that breaks GStreamer for some reason.
# That is also the reason why LD_LIBRARY_PATH can't be set globally.
FFPROBE_PATH=$(PATH=/ffmpeg/bin:$PATH which ffprobe)
LD_LIBRARY_PATH=/ffmpeg/lib "$FFPROBE_PATH" "$@"
