#!/usr/bin/with-contenv bash

source /helpers/logger.sh
source /helpers/set_env.sh

touch /tmp/go2rtc.yaml
chown -R --silent abc:abc /tmp/go2rtc.yaml || :

rm -f $VISERON_CONFIG_DIR/go2rtc.log

log_info "Starting go2rtc..."
exec justc-envdir /var/run/environment s6-setuidgid abc exec go2rtc --config /tmp/go2rtc.yaml 2>&1 | tee -a $VISERON_CONFIG_DIR/go2rtc.log
