#!/usr/bin/with-contenv bash

source /helpers/logger.sh

log_info "***************** Getting GStreamer path *****************"
export VISERON_GSTREAMER_PATH=$(which gst-launch-1.0)
printf "$VISERON_GSTREAMER_PATH" > /var/run/environment/VISERON_GSTREAMER_PATH
log_info "GStreamer path: $VISERON_GSTREAMER_PATH"
log_info "*********************** Done *****************************"
