"""NVR constants."""
from typing import Any, Dict, List

COMPONENT = "nvr"

# COORDINATES_SCHEMA
CONFIG_X = "x"
CONFIG_Y = "y"


# LABEL_SCHEMA
CONFIG_LABEL_LABEL = "label"
CONFIG_LABEL_CONFIDENCE = "confidence"
CONFIG_LABEL_HEIGHT_MIN = "height_min"
CONFIG_LABEL_HEIGHT_MAX = "height_max"
CONFIG_LABEL_WIDTH_MIN = "width_min"
CONFIG_LABEL_WIDTH_MAX = "width_max"
CONFIG_LABEL_TRIGGER_RECORDER = "trigger_recorder"
CONFIG_LABEL_REQUIRE_MOTION = "require_motion"
CONFIG_LABEL_POST_PROCESSOR = "post_processor"

DEFAULT_LABEL_CONFIDENCE = 0.8
DEFAULT_LABEL_HEIGHT_MIN = 0
DEFAULT_LABEL_HEIGHT_MAX = 1
DEFAULT_LABEL_WIDTH_MIN = 0
DEFAULT_LABEL_WIDTH_MAX = 1
DEFAULT_LABEL_TRIGGER_RECORDER = True
DEFAULT_LABEL_REQUIRE_MOTION = False
DEFAULT_LABEL_POST_PROCESSOR = None


# ZONE_SCHEMA
CONFIG_COORDINATES = "coordinates"
CONFIG_ZONE_NAME = "name"
CONFIG_ZONE_LABELS = "labels"


# OBJECT_DETECTOR_SCHEMA
CONFIG_DETECTOR = "detector"
CONFIG_FPS = "fps"
CONFIG_LABELS = "labels"
CONFIG_MAX_FRAME_AGE = "max_frame_age"
CONFIG_LOG_ALL_OBJECTS = "log_all_objects"
CONFIG_MASK = "mask"

DEFAULT_FPS = 1
DEFAULT_LABELS: List[Dict[str, str]] = []
DEFAULT_MAX_FRAME_AGE = 2
DEFAULT_LOG_ALL_OBJECTS = False
DEFAULT_MASK: List[Dict[str, int]] = []


# MOTION_DETECTOR_SCHEMA
CONFIG_TRIGGER_DETECTOR = "trigger_detector"

DEFAULT_TRIGGER_DETECTOR = True


# NVR_SCHEMA
CONFIG_OBJECT_DETECTOR = "object_detector"
CONFIG_MOTION_DETECTOR = "motion_detector"
CONFIG_ZONES = "zones"

DEFAULT_ZONES: List[Dict[str, Any]] = []
