steps:
  - script: |
      df -h
    displayName: List free space before cleaning
  - script: |
      docker rmi -f $(docker images -aq) || true
    displayName: Clean up Docker images
  - script: |
      docker system prune --force --all --volumes || true
    displayName: Docker prune
  - script: |
      sudo rm -rf /usr/local/lib/android || true
      sudo rm -rf /usr/local/.ghcup || true
      sudo rm -rf /opt/hostedtoolcache/CodeQL || true
    displayName: Remove unused files
  - script: |
      df -h
    displayName: List free space after cleaning
