parameters:
  - name: release
    type: boolean
    default: false

steps:
  - script: |
      set -e
      branch="$(Build.SourceBranchName)"

      if [ "$branch" == "dev" ] ; then
        version="dev"
      elif [ "$branch" == "docker_revamp" ] ; then
        version="docker_revamp"
      elif [[ "$branch" == *"refs/tags/v"* ]] ; then
        version=$([[ $branch =~ refs/tags/v(.*) ]] && echo "${BASH_REMATCH[1]}")
      else
        echo "Failed to extract version from branch $branch"
        exit 255
      fi

      echo Extracted version is $version
      echo "##vso[task.setvariable variable=viseronVersion;]$version"
    condition: ${{ parameters.release }}
    displayName: Extract version from branch name
