trigger:
  branches:
    include:
      - docker_revamp

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    displayName: Register QEMU for cross-builds
  - script: |
      cd $(Agent.BuildDirectory)/s
      ls -al

      architectures="amd64 rpi3"
      for architecture in ${architectures}; do
        docker-compose --file docker-compose-build.yaml build ${architectures}-ffmpeg
      done
    displayName: "Run a one-line script"
