trigger: none

pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: viseronModels
      source: "Viseron Models"
      trigger:
        branches:
          - dev
          - docker_revamp

jobs:
  - template: templates/build.yaml
    parameters:
      image: base
