trigger:
  branches:
    include:
      - docker_revamp

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: docker run --rm --privileged multiarch/qemu-user-static:register --reset
    displayName: Register QEMU for cross-builds
  - script: |
      cd $(Agent.BuildDirectory)/s/docker
      ls -al

      architectures="amd64 rpi3"
      for architecture in ${architectures}; do
        echo Building FFmpeg for ${architecture}
        docker-compose --file ../azure-pipelines/docker-compose-build.yaml --env-file ../azure-pipelines/.env build ${architecture}-ffmpeg
      done
    displayName: Build FFmpeg
