trigger:
  branches:
    include:
      - docker_revamp
      - dev
      - master
  paths:
    include:
      - requirements.txt

jobs:
  - template: templates/build.yaml
    parameters:
      image: wheels
