trigger:
  branches:
    include:
      - docker_revamp
      - dev
      - master
  paths:
    include:
      - requirements.txt

pool:
  vmImage: "ubuntu-latest"

resources:
  pipelines:
    - pipeline: viserondlib
      source: "Viseron dlib"
      trigger:
        branches:
          - dev
          - docker_revamp

jobs:
  - template: templates/build.yaml
    parameters:
      image: wheels
