trigger: none

resources:
  pipelines:
    - source: Viseron Pipelines
      pipeline: Viseron Base
      trigger:
        branches:
          include:
            - dev
            - docker_revamp

jobs:
  - template: templates/build.yaml
    parameters:
      image: models
      imageNameOnly: true
      architectures:
        - amd64
