trigger:
  branches:
    include:
      - docker_revamp

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      architectures="amd64 rpi3"
      for architecture in ${architectures}; do
        echo ${architecture}
      done
    displayName: "Run a one-line script"
