trigger: none

resources:
  pipelines:
    - pipeline: Viseron Pipeline
      source: Viseron
      trigger:
        branches:
          include:
            - dev
jobs:
  - template: templates/build.yaml
    parameters:
      image: base
